### ISSUE TITLE
User running into CSRF errors

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1100]
Mike Best, a pretty regular user, keeps running into this error message. 

![unnamed](https://cloud.githubusercontent.com/assets/136939/20570971/a96408d2-b173-11e6-92a9-8679f1b10d30.png)

Might be due to the changed certs?

**Comment by allanlasser** [comment]
Shawn reported hitting this error as well, but the issue disappeared after a refresh.

**Comment by mitchelljkotler** [comment]
I need ot put more logging in to see why Mike is getting this constantly.  Getting it once might be possible if you leave a window open too long or something like that, but if its never working for Mike there has to be something up with his referer header or cookies.

**Comment by freddymartinez9** [comment]
I also saw this on Chrome, using uBlock origin and MacOS Sierra.

**Comment by mitchelljkotler** [comment]
@freddymartinez9 I think the most likely cause is either an issue with the CSRF cookie being blocked or by the browser blocking the  referer header which is used in the check.  I have put in additional logging, if you run into this error again please let me know the approximate time and I will check the logs.

**Comment by mitchelljkotler** [comment]
You get a new CSRF token when you log in - it seems like at least some of Mike Best's errors are due to opening multiple tabs from his notification emails which include a log in token, causing one login per tab, meaning all but the last tab will have an outdated token.  One solution to this might be to ignore login tokens if the user is already logged in.
