### ISSUE TITLE
Agency claims attachment didn't go through.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1137]
I sent a form along with an Admin Fix, but the agency claims that it didn't receive it. I can't tell whether the attachment didn't actually go through (it appears, from the request page, that it did, and, of course, if it didn't that's a general problem) or if this agency is being irritating and trying to get me to submit my complaint via their online form (it's that sort of day, so perhaps I'm expecting ill will where there is none).  

This is the message I sent:
https://www.muckrock.com/foi/olathe-14588/geofeedia-inc-contracts-invoices-social-media-surveillance-policies-olathe-police-department-29857/#comm-325409
https://www.muckrock.com/foi/raw_email/325409/

**Comment by morisy** [comment]
Hi Beryl!

Best way to double check on if attachments actually go out is peak into diagnostics; the emails in there are just BCCs of actual me so they're exactly what the agency should receive. It looks like the attachment was included properly, so maybe their email system is stripped it or something, but the problem is on their end, not ours. We could also try sending them a link to the form hosted on our site if their email system is stripping attachments?
