### ISSUE TITLE
Indication of how a communication was sent.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1167]
With faxaway, I was able to check the raw email to see whether something was sent as a fax or, if there was no raw email option, that it was sent via snail mail. The new option doesn't give such a thing. Talking briefly with Michael just now, good option may be to have in that dropdown menu (the one where we can resend/delete/check the status/raw email of a request) the method by which the comm. was sent and, if it was faxed, a link to the Phaxio status page.

**Comment by blipblitz** [comment]
Related: I just tried resending this via the new method, though the raw email option still appears and indicates it was sent via faxaway.

https://www.muckrock.com/foi/united-states-of-america-10/materials-for-the-game-collection-deck-35175/#resend-350867-form

**Comment by mitchelljkotler** [comment]
1) You can check this on the backend: ie https://www.muckrock.com/admin/foia/foiacommunication/352242/change/ (I know this isn't as useful as it being in the drop down)
2) I can add a link to the phaxio dashboard page so this information is easily viewable from the front end
3) I already resent that one
4) It has a raw email because it was originally sent before the Phaxio switch (hence it has the raw email to faxaway, which subsequently failed)
5) I then resent it using Phaxio (and it succeeded)

**Comment by mitchelljkotler** [comment]
The backend page also has all the information on any errors from this communication (and any opens)

**Comment by blipblitz** [comment]
1. Aha! Thank you! 
2. Yes, that may be nice.
3. Lol, oops, it was hard to tell
4. Will that be updated or should I just avoid "resend" in this way?
5. Huzzah!
6. Also huzzah!

**Comment by mitchelljkotler** [comment]
3. I resolved the failed fax task (that was my way of indicating it)
4. This make me kind of want to rethink how resends work - since you right now can't keep track of which "version" any errors are on, (especially if you need to resend multiple times), and can't properly keep track if a resend is sent somewhere else than the original.  So in the short term, no change, but it shouldn't be a common occurrence once we are all done with faxaway.  In the long term I would like to have resends actually create a new communication and hide the failed communication on the frontend... or something like that
