### ISSUE TITLE
Forum Spam

### ISSUE THREAD

**Issue by dwin** [MuckRock/muckrock#1227]
There should be a method to flag posts and comments as spam for moderation. 

Examples of Questions:

- https://www.muckrock.com/questions/online-exam-preparation-857
- https://www.muckrock.com/questions/laundry-service-in-vaishali-853
- https://www.muckrock.com/questions/alleppey-houseboat-855
- https://www.muckrock.com/questions/kerala-taxi-854
- https://www.muckrock.com/questions/how-do-i-request-to-you-842

Examples of Comments:
- https://www.muckrock.com/questions/broad-request-830#answer-935
- https://www.muckrock.com/questions/how-do-i-request-muckrock-to-turn-on-the-pay-tab-775#answer-849
- https://www.muckrock.com/questions/how-do-i-request-muckrock-to-turn-on-the-pay-tab-775#answer-860
- https://www.muckrock.com/questions/how-do-i-request-muckrock-to-turn-on-the-pay-tab-775#answer-863
- https://www.muckrock.com/questions/best-way-to-write-a-foia-for-employee-employee-emails-825#answer-882

**Comment by morisy** [comment]
Thanks so much! Yes, things have gotten really out of hand.

At some point, the forum needs more more serious revamping, but for now I think the quickest solution is to add the "Get Help" button and a little text "Flag" link that activates the same functionality to let users report spam posts so that we at least have some process for weeding out spam issues.

Mitch, let me know if you have questions about that — basically just turning on flags for Q&A, and having a little "Flag" text link on each question/comment.

**Comment by morisy** [comment]
Also cleaned out these particularly spams, and will try and do a bigger pass later.

**Comment by mitchelljkotler** [comment]
So you need to be logged in to ask a question which means the spammers are taking the time to create accounts.  When you deleted the spam did you also delete the offending user accounts?  I feel like we want something more than a simple flag so we can one click delete spam and accounts.

**Comment by mitchelljkotler** [comment]
#1258 supersedes this
