### ISSUE TITLE
Tracking number grabbing wrong tracking numbers

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1276]
Three examples:

https://www.muckrock.com/foi/united-states-of-america-10/nancy-friday-fbi-file-45634/
https://www.muckrock.com/foi/united-states-of-america-10/henry-christensen-iii-fbi-file-45692/
https://www.muckrock.com/foi/united-states-of-america-10/spy-plane-over-dprk-45750/

I think for this to work the regex will have to be customized per agency and a little stricter. Putting in wrong tracking numbers is worse than none. Also one good check would be to first look if that number appeared in the original request: If it did, there's no chance that it's the tracking number.

**Comment by morisy** [comment]
Maybe one way to implement in the meantime is to put a "We think this is the tracking number for the request." and let people click a little "Confirm" or "Incorrect" link below to either add or discard it, and then use that to gauge when the regexes work well enough.

**Comment by morisy** [comment]
Marking as high just to turn the current system off; getting it working is somewhat lower priority and priority can be adjusted once turned off.

**Comment by mitchelljkotler** [comment]
I was hoping a nice relaxed regex would get good results - but since it isn't I switched it to something very strict at the moment (Only matches on "Tracking Number: ..."),  This should not yield any false positives.  Any time someone sees a nicely formatted one that is not automatically detected that can forward it to me and I'll add another regex.
