### ISSUE TITLE
Export Request Search Results as CSV

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1282]
So I was thinking of what could make the mapping easier while also being a generally useful feature for users,  and I think an "Export Search Results" feature would be good. Basically, any search results query would have an "Export as CSV" button. This button would be greyed out unless you have a Pro, Org, or Staff account. If you don't, it will say "Exporting Search Results is a Pro feature. Upgrade here." with a link to the page to upgrade your account.

Fields to export:

user | title | absolute_url | status | jurisdiction | jurisdiction ID |  agency | agency ID | date_followup | description | pages | location data of agency?

**Comment by blipblitz** [comment]
Might there be a way to include the amount of money that had been paid to it? I can imagine it being useful to be able to quickly see how much was paid or asked for on a batch of requests. 

Other eventually potentially-useful fields (though some seem to be a few steps more):
- associated FOIA tracking numbers
- days since it was submitted 
- days since last response
- whether it's associated with a particular project 
- tags
- embargoed or no 
- appealed ever?
- ECD 

CSV exciting!

**Comment by morisy** [comment]
Those all seem like good fields to add!

Adanya also suggested that it'd be good to have this on Project pages for people who are part of that project. Slightly redundant but think it's worth it.
