### ISSUE TITLE
Incoming FOIA Portal Task Communication Link Handling broken

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#1291]
So there's some weird Markdown related (I think) bug with incoming portal tasks, where the incoming link is pseudo markdown:

<img width="1131" alt="bug" src="https://user-images.githubusercontent.com/136939/33450287-5068806a-d5d9-11e7-8240-9c59fd909b8d.png">

Which isn't that bad except then the actual hyper link points to '''
'''
http://E4d5132a685bea183861f69cf4fcc10f887fa3a7e_Q21916_D1949800.pdf](https://efoia.fbi.gov/download-file/submission-4d5132a685bea183861f69cf4fcc10f887fa3a7e/NjtLkIbq6THAuXk/E4d5132a685bea183861f69cf4fcc10f887fa3a7e_Q21916_D1949800.pdf)"
'''
which is a bad link which makes completing the task more complicated.

**Comment by mitchelljkotler** [comment]
So the problem is on all communications, not just portal tasks.  The Django urlize template filter does not handle these links correctly due to the way they are formatted.  I tried replacing them with bleach.linkify, which processes them correctly, but turned out to be unbearably slow.  Will try to come up with a reasonable solution.
