### ISSUE TITLE
"Did Not Mail" in Snail Mail Task doesn't set any status on the corresponding request

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1360]
This has caused a few requests to be left as "Processing" when that's not right. We should maybe have it default to the previous status.

**Comment by mitchelljkotler** [comment]
Did not mail does not imply any action, so I don't think it should change the status - whatever somebody did to send it out by another means should be updating the status.  Defaulting to the previous status is bad because we don't keep track of the previous status and it is very likely (for new requests) the previous status is draft which is definitely not right.  How are these being follow up on and can we set the status there?

Also, meta comment: It is useful to provide context for github issues

**Comment by mitchelljkotler** [comment]
So the status is set correctly on a resend or follow up as far as I can tell - gonna won't fix this unless actual erroneous behavior is discovered
