### ISSUE TITLE
Flag us when an email is returned on an agency that has no set email address.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1373]
Sometimes we send something out in Snail Mail and we get a response via email.

In these cases, it's important that we add the email address to the agency so that future requests are automatically emailed rather than snail mailed. It would also probably be for the best if we can send follow ups on other requests to the email address rather than continuing to snail mail them.

However, we don't have a good system for knowing when we've actually got a working email address somewhere associated with an agency. If there were a way for us to know that we should add the email to the agency, that would be helpful.

**Comment by blipblitz** [comment]
Can we move this up the priority list?

**Comment by morisy** [comment]
I think this is a good idea, not sure what a good implementation is. I feel like auto-adding email addresses is a bad idea because a lot of agencies want you to mail the initial request, and then the may follow up via email. Adding whatever employee emails you seems like it would end up sticking up a lot of things (let me know if you disagree).

Would it make sense to bundle this in somehow into the "Review Agency" task? Add another line that says "These emails were used by this agency to respond to requests over the last 60 days" or whatever?

**Comment by mitchelljkotler** [comment]
So the email will automatically be associated with the agency, but not used as the primary means of communication automatically.  Beryl wants some sort of notification - (a Flag or an email to info maybe?) - so a human can review and make it the primary if appropriate.  I don't think review agency is a great place for it, because its entirely possible for this situation to arise without any review agency task.

And yes, I can try to get to this this week.
