### ISSUE TITLE
upload_document_cloud should send the jurisdiction to DocumentCloud as data key-values

### ISSUE THREAD

**Issue by advayDev1** [MuckRock/muckrock#1743]
DocumentCloud API allows sending key-values.
For govt communication attachments, should send jurisdiction:[City] and jurisdictionParent:[State] over in the upload api.

That would allow us to distinguish between all the, for example, source:"Office of Mayor" documents in DocumentCloud.

**Comment by bfeldman89** [comment]
I feel so seen! Maybe even grant the requester access to editing the custom data key/value pairs 😬...

I used DocumentCloud for years before getting a MuckRock account. It's nice that I can manually add PDFs I receive from MuckRock requests to the relevant DocumentCloud projects (I think streamlining/automating this with MuckRock "projects" would be an amazing feature, but I digress), but I _really_ miss being able to use custom key/value pairs to organize larger projects further. 

For example, I had a project with 523 documents from a project requesting body cam policies in MS. I had custom data for jurisdiction, agency, and type of record.

![image](https://user-images.githubusercontent.com/26087892/87211624-f7da5d00-c2df-11ea-9e74-5e0d2ae35dcb.jpeg)

Now that I've resumed the project but via my MuckRock account, I've acquired 10 additional policies. I manually added them to the project one by one, but that's all I have the ability to do because the contributor is MuckRock, not me. 😔

![image](https://user-images.githubusercontent.com/26087892/87211634-0a549680-c2e0-11ea-9b08-ddec686ced6f.jpeg)

**Comment by mitchelljkotler** [comment]
With the new DocumentCloud we will eventually be syncing your MuckRock documents with your own DocumentCloud account, which will help resolve some of these issues.  We can also set some custom key-value pairs when we make that switch - jurisdiction and agency should be easy to do.

**Comment by advayDev1** [comment]
Looks like this was closed by 328b8c9d09661ad427a86e34adaaf8c9157b0bca - excellent thank you!

**Comment by advayDev1** [comment]
Actually @mitchelljkotler I noticed all the recent records have the new jurisdiction and request and agency fields - any chance MuckRock would run a task over all the old documents to update their DocumentCloud data fields?  Would make analysis a lot easier.  Thanks!
