### ISSUE TITLE
FOIA Log

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/muckrock#1809]
- [ ] data
- [ ] copy
- [ ] release announcement

**Comment by amandabee** [comment]
Documentation of how to write up the data lives at: https://www.notion.so/muckrock/FOIA-Log-Upload-Guide-e9e000ed060f4283970adced70370769

**Comment by morisy** [comment]
Some further iterations for FOIA Log @mitchelljkotler  — I think most of these should be small lifts but happy to run through and modify. These would be breaking changes so old logs would need to be re-uploaded.
* New Entity, FOIA Log, that serves as a parent to FOIA Log entries.
  * Fields include (Asterisks for required ones):
    * Agency*
    * Start Date Range*
    * End Date Range*
    * Contributed By (MuckRock User Picker)
    * Internal Note
    * Source* (Text field, can be a link to a FOIA reading room, MuckRock request, or note stating that so and so emailed it to us)
    * Who uploaded the log* (private just for internal use)
  * Created whenever a new FOIA log is uploaded, additional fields add by uploading users
* Move title bar from bottom of the request to the top
  * The slightly grey title bar is confusing at the bottom, and people naturally click the agency name instead of the title of the request if they want more details. This should be changed on both the list view and the individual log view.
* List agencies that have FOIA logs, as well as the individual available logs, on the sidebar of the list viewer. Clicking an agency name will do a search for all FOIA entries from that agency, while clicking a specific log will show just entries from that specific log.

![Image](https://github.com/MuckRock/muckrock/assets/136939/cf153049-58bd-4fc2-b1a5-81bb1c4391e9)

  * Eventually we’d also want to list the FOIA logs from a specific agency on the agency page.

**Comment by allanlasser** [comment]
I suggest closing this issue since the feature has been released and the items on @mitchelljkotler and @amandabee's punch lists have been completed.

For the iterative changes @morisy flagged, might be best to make them individually addressable issues. I could accomplish #2 and #3 fairly easily, since they don't require any backend or data changes. I believe #4 is already done, there's a FOIA Log tab on Agency pages that lists the 25 most recent logs, with a link to a prefiltered list view (similar to requests).

**Comment by mitchelljkotler** [comment]
I have started a branch working on the data changes for the first point.  The third point definitely is dependent on the data model change, to link FOIA Log entries to a particular FOIA Log grouping.
