### ISSUE TITLE
Show submitter of info on New Agency Task

### ISSUE THREAD

**Issue by morisy** [MuckRock/muckrock#849]
It'd be useful to see _who_ submitted the info saved in new agency tasks to evaluate the quality of the data.

I think that in the future, this data might be different than the person who filed the request/created the agency once we started crowdsourcing data, so might want to keep it stored as a separate identifier rather than just including the user's name, but your call

**Comment by morisy** [comment]
So for new agency tasks, it would still be useful to show the user who submitted the new agency, the user who submitted the tentative information in the new agency task (right now, always the same as the user who submitted the new agency), and any requests associated with that new agency as well as their current status (just draft or processing). This helps when deciding if it's ok to just rejected and reassign something if it's a nonsense request someone submitted as a draft while playing around with the site or in case of spammers. Seen a small uptick in the latter.

**Comment by mitchelljkotler** [comment]
So since you can only pick approved agencies, no new agency should have more than one request (the one where it was created).  It is possible that this wasn't true in the past, but fixing the bug that allowed submitting to phantom agencies should also stop a new agency from having multiple requests.  If this is not the desired behavior we should rethink how we want this to work.
